services:
  laa-claim-for-payment:
    image: "${LAA_CLAIM_FOR_PAYMENT_IMAGE}"

  stub-civil-claims-api:
    image: "${LAA_CLAIM_FOR_PAYMENT_STUBS_CIVIL_CLAIMS_API_IMAGE}"

  stub-oidc-server:
    image: "${LAA_CLAIM_FOR_PAYMENT_STUBS_OIDC_SERVER_IMAGE}"

  laa-claim-for-payment-frontend:
    image: "${LAA_CLAIM_FOR_PAYMENT_FRONTEND_IMAGE}"

  laa-assess-a-claim-frontend:
    image: "${LAA_ASSESS_A_CLAIM_FRONTEND_IMAGE}"