services:
  laa-claim-for-payment:
    ports:
      - "8080:8080"
      - "8079:8079"
    environment:
      SECURITY_ENABLED: true
      CIVILCLAIMS_API_BASE_URL: http://stub-civil-claims-api:8090
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://stub-oidc-server:8091
      AUTH_SCOPES_CLAIMS_WRITE: SCOPE_https://claims-api/claims_write
    depends_on:
      stub-oidc-server:
        condition: service_healthy

  stub-civil-claims-api:
    ports:
      - "8090:8090"
    environment:
      SECURITY_ENABLED: true  
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://stub-oidc-server:8091

  stub-oidc-server:
    ports:
      - "8091:8091"
    volumes:
      - ./stub.yml:/opt/stub-oidc-server/config/external.yml:ro
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8091/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  laa-claim-for-payment-frontend:
    ports:
      - "3000:3000"
      - "2999:2999"
    environment:
      BASE_URL: http://localhost:3000
      API_URL: http://laa-claim-for-payment:8080
      AUTH_ENABLED: true
      ISSUER_BASE_URL: http://stub-oidc-server:8091
      REDIS_DISABLED: true
      REDIS_URL: redis://localhost:6379
      SESSION_SECRET: s3Cur3
      SESSION_NAME: sessionId
      OIDC_SCOPE: openid profile email
      CLAIMS_API_SCOPE: https://claims-api/claims_write
      OIDC_LOGIN_PATH: /login
      OIDC_CLIENT_SECRET: caa-mock-secret
      OIDC_CALLBACK_PATH: /callback
      OIDC_LOGOUT_PATH: /logout
      CLIENT_ID: caa-client
      SERVICE_NAME: Claim for Controlled Work
      MANAGEMENT_PORT: 2999
    depends_on:
      - laa-claim-for-payment

  laa-assess-a-claim-frontend:
    ports:
      - "3001:3001"
      - "2998:2998"
    environment:
      BASE_URL: http://localhost:3001
      API_URL: http://laa-claim-for-payment:8080
      AUTH_ENABLED: true
      ISSUER_BASE_URL: http://stub-oidc-server:8091
      REDIS_DISABLED: true
      REDIS_URL: redis://localhost:6379
      SESSION_SECRET: s3Cur3
      SESSION_NAME: sessionId
      OIDC_SCOPE: openid profile email
      CLAIMS_API_SCOPE: https://claims-api/claims_write
      OIDC_LOGIN_PATH: /login
      OIDC_CLIENT_SECRET: afe-mock-secret
      OIDC_CALLBACK_PATH: /callback
      OIDC_LOGOUT_PATH: /logout
      CLIENT_ID: afe-client
      SERVICE_NAME: Assess Claim for Civil Work
      MANAGEMENT_PORT: 2998
    depends_on:
      - laa-claim-for-payment
