services:
  laa-claim-for-payment:
    build:
      context: ../laa-claim-for-payment/claim-for-payment-service
      dockerfile: Dockerfile

  stub-civil-claims-api:
    build:
      context: ../laa-claim-for-payment-stubs/stub-civil-claims-api
      dockerfile: Dockerfile
      
  stub-oidc-server:
    build:
      context: ../laa-claim-for-payment-stubs/stub-oidc-server
      dockerfile: Dockerfile

  laa-claim-for-payment-frontend:
    build:
      context: ../laa-claim-for-payment-frontend
      dockerfile: Dockerfile

  laa-assess-a-claim-frontend:
    build:
      context: ../laa-assess-a-claim-frontend
      dockerfile: Dockerfile