env:
  contexts:
    - name: Authenticated
      urls:
        - http://localhost:3000
      includePaths:
        - http://localhost:3000.*
      authentication:
        method: browser
        parameters:
          loginPageUrl: http://localhost:3000
          loginPageWait: 10
          browserId: firefox
          stepDelay: 0
          diagnostics: false
          steps: []
        verification:
          method: poll
          loggedInRegex: \QSign out\E
          pollFrequency: 60
          pollUnits: requests
          pollUrl: http://localhost:3000
          pollPostData: ""
      sessionManagement:
        method: cookie
      technology: {}
      structure: {}
      users:
        - name: alice
          credentials:
            password: password
            username: alice
  parameters: {}
jobs:
  - type: requestor
    parameters:
      user: alice
    requests:
      - url: http://localhost:3000
        method: ""
    alwaysRun: true
  - type: spider
    parameters:
      context: Authenticated
      user: alice
      url: http://localhost:3000
      parseDsStore: null
    alwaysRun: true
  - type: activeScan
    parameters:
      context: Authenticated
      user: alice
      url: http://localhost:3000
    policyDefinition:
      defaultStrength: medium
      defaultThreshold: medium