env:
  contexts:
    - name: Authenticated
      urls:
        - ${TARGET}
      includePaths:
        - ${TARGET}.*
      authentication:
        method: browser
        parameters:
          loginPageUrl: ${TARGET}
          loginPageWait: 10
          browserId: firefox
          stepDelay: 0
          diagnostics: false
          steps: []
        verification:
          method: poll
          loggedInRegex: \QSign out\E
          pollFrequency: 60
          pollUnits: requests
          pollUrl: ${TARGET}
          pollPostData: ""
      sessionManagement:
        method: cookie
      technology: {}
      structure: {}
      users:
        - name: alice
          credentials:
            password: password
            username: alice
  parameters: {}
jobs:
  - type: requestor
    parameters:
      user: alice
    requests:
      - url: ${TARGET}
        method: GET
    alwaysRun: true
  - type: spider
    parameters:
      context: Authenticated
      user: alice
      url: ${TARGET}
      parseDsStore: null
    alwaysRun: true
  - type: passiveScan-wait
    parameters: {}
#  - type: activeScan
#    parameters:
#      context: Authenticated
#      user: alice
#      url: ${TARGET}
#    policyDefinition:
#      defaultStrength: medium
#      defaultThreshold: medium
  - type: report
    parameters:
      template: traditional-html
      theme: null
      reportTitle: ZAP by Checkmarx Scanning Report
    risks:
      - low
      - medium
      - high
    confidences:
      - low
      - medium
      - high
      - confirmed
    sections:
      - insights