external:
  users:
    - username: alice
      displayName: Alice Smith
      email: alice.smith@example.test
      firmId: prov-123
      providerUserId: 68fb8dc1-2c2e-4113-8c37-242d476edf11
      password: password
      roles:
        - caseworker
    - username: bob
      displayName: Bob Jones
      email: bob.jones@example.test
      firmId: prov-456
      providerUserId: c2379c93-2697-405f-b7d8-b8977c80d0c8
      password: password
      roles:
        - admin